name: cs230
channels:
  - conda-forge
dependencies:
  - python=3.10.11
  - pandas
  - numpy
  - plotly
  - scikit-learn
  - scipy=1.10.0
  - statsmodels
  - tensorflow
  - notebook
  - black
  - matplotlib
  - python-kaleido
  - gitpython